### ISSUE TITLE
Add business plan plot

### ISSUE THREAD

**Issue by davide-f** [SPSUnipi/EnergyCommunity.jl#11]
It is useful to add a function into ECModel.jl to show the business plan.
Something like the following image:
![image](https://github.com/SPSUnipi/EnergyCommunity.jl/assets/67809479/16d0b57f-1af5-4aff-be4e-8f775eeca01a)

The function shall have as mandatory argument only the ECModel, as optional arguments an object that specifies what user shall be plotted and a second object representing the specific final distribution allocation of the total profit.
This last parameter by default is nothing, which means that the overall costs are highlighted, whereas if a specific user is requested the plot the business plan of that specific user is plotted.
As a remark, when a specific user is requested, the additional input of the final distribution allocation is needed to specify how to distribute the rewards across the users

**Comment by davide-f** [comment]
@TomFer97 , we discussed about this, may you be interested in addressing this issue? :)

**Comment by TomFer97** [comment]
Absolutely, I'll open a Pull request asap

**Comment by davide-f** [comment]
Awesome! :)

As a guideline, I feel like the procedure could be as follows:
1. add DataFrames in the dependencies (from REPL "] add DataFrames")
2. in the Project.toml, add a line for DataFrames in compact 'Dataframes = "1"'  [This is needed for publishing the new release of EnergyCommunity v0.1.1 (example)]
3. add a function to describe the business plan. The function shall return in output a DataFrame where in the columns we have the different economic quantities and in the rows there are the different quantities for different years. Once column shall also be "year" to track that
4. add a plotting function to plot the business plan. This function internally calls the function created in point 3 and then plot the outputs.

Both functions created in 3 and 4 shall have an optional argument to describe what user the business plan belongs to, as described in the introduction of this issue

**Comment by davide-f** [comment]
REP stands for replacement. They are the costs to replace the components once they reach their lifetime.

RV stands for recover value. They represent equivalent revenues for the components that at the end of the project could last longer. For example, if PVs last 25y but the project last 20, at the end of the project a 20% (5/25) of the value of the PV is reimbursed

**Comment by davide-f** [comment]
RV is always 0 for all years but the last

**Comment by davide-f** [comment]
Closed by #12
